theme = "tokyonight_storm"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
auto-completion = true
auto-format = true

[editor.statusline]
left = ["mode"]
center = []
right = ["file-name", "diagnostics", "selections", "file-encoding", "file-line-ending", "file-type", "spinner"]
separator= "|"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
select = "underline"
insert = "bar"
normal = "block"

[editor.auto-pairs]
'<' = '>'

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "╎"

