decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10

    active_opacity = 0.9
    inactive_opacity = 0.5
    blur {
        enabled = true
        size = 7
        passes = 2
        new_optimizations = true
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}
