return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  dependencies = {
    "williamboman/mason.nvim",
    "williamboman/mason-lspconfig.nvim",
  },
  config = function()
    require("mason-tool-installer").setup({
      auto_update = true,
      run_on_start = true,
      ensure_installed = {
        "bashls",
        "clangd",
        "cmake",
        "cssls",
        "dockerls",
        "docker_compose_language_service",
        "efm",
        "gopls",
        "html",
        "jsonls",
        "lua_ls",
        "marksman",
        "pyright",
        "sqlls",
        "taplo",
        "tsserver",
        "yamlls",
        "shellcheck",
        "stylelint",
        "prettier",
        "shfmt",
        "cpplint",
        "clang-format",
        "hadolint",
        "gitlint",
        "golangci-lint",
        "goimports",
        "eslint",
        "jq",
        "luacheck",
        "stylua",
        "flake8",
        "black",
        "isort",
        "ansible-lint",
        "yamllint",
      },
    })
  end,
}
