source "$HOME/.antigen/antigen.zsh"

antigen use oh-my-zsh

antigen bundle fzf
antigen bundle zsh-interactive-cd
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

alias ls="exa -lgh"
alias lzg="lazygit"
alias dc="docker compose"
alias dcu="docker compose up"
alias dce="docker compose exec"
alias dcb="docker compose build --ssh default=$HOME/.ssh/id_rsa"
alias dcd="docker compose down"
alias dcr="docker compose run"
alias dctest="docker compose run test pytest"

export function venv() {
  v=$1
  source "$HOME/Repos/.venvs/$v/bin/activate"
}

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1
export PATH="$HOME/.local/share/fnm:$HOME/go/bin:$HOME/.cargo/bin:$HOME/.local/bin:$HOME/.npm-global/bin:$PATH"


eval "$(fnm env)"
eval "$(starship init zsh)"
